version: "3.9"
services:
  web:
    image: docker.io/infracloudio/csvserver
    ports:
      - "9393:9300"
    volumes:
      - /opt/csvserver/inputdata:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange  
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
       - "9090:9090"
   volumes:
     - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
   links:
     - "csvserver:csvserver"

